apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: tix
deploy:
  kubectl:
    manifests:
    - infrastructure/k8s/*
    - infrastructure/k8s/dev/*
build:
  local:
    push: false
  artifacts:
    - image: elevenhotdogs/tix.auth
      context: packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: elevenhotdogs/tix.client
      context: packages/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: elevenhotdogs/tix.tickets
      context: packages/tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: elevenhotdogs/tix.orders
      context: packages/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: elevenhotdogs/tix.expiration
      context: packages/expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: elevenhotdogs/tix.payments
      context: packages/payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

