apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: tix
deploy:
  kubectl:
    manifests:
    - infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: elevenhotdogs/tix.auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
