apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: elevenhotdogs/tix.client
          imagePullPolicy: IfNotPresent
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: base_url
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-key
                  key: STRIPE_PUBLISHABLE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
