name: Deploy k8s manifests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/k8s/**'
      - '!infrastructure/k8s/dev/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: DigitalOcean authentication
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_K8S_TOKEN }}
      - name: Apply manifests
        run: kubectl apply -f infrastructure/k8s -f infrastructure/k8s/prod
